[pytest]
minversion = 8.0
xfail_strict = true
log_cli_level = INFO
addopts =
    -vv
    -rA
    --cov=bornsim
    --cov-report=term-missing
    --cov-report=html
    --cov-config=.coveragerc
    --capture=tee-sys
    --import-mode=importlib
testpaths =
    tests/analytical
    tests/numerical
    tests/packaging
python_files = test_*.py
python_functions = test_*
